--
-- DESTROY SCHEMA
--

-- DROP EXTENSION IF EXISTS fetchq CASCADE;
-- DROP EXTENSION IF EXISTS "uuid-ossp";

-- DROP SCHEMA IF EXISTS fetchq CASCADE;
-- DROP SCHEMA IF EXISTS fetchq_data CASCADE;
-- DROP SCHEMA IF EXISTS fetchq_test CASCADE;

-- DROP SCHEMA IF EXISTS public CASCADE;
-- CREATE SCHEMA public;



